### ISSUE TITLE
Problem with libxlsxwriter during TalysLib installation

### ISSUE THREAD

**Issue by ilyadash** [terawatt93/TalysLib#5]
Попробуем воспользоваться вкладкой Issues на GitHub! 
Я скачал библиотеку TalysLib из репозитория  terawatt93/TalysLib и попытался её установить согласно инстркуции. При запуске скрипта MakeLibraries.sh в скачанной директории терминал выдал ошибку:

In file included from input_line_12:3:
./TalysLib.hh:23:10: fatal error: 'libxlsxwriter/include/xlsxwriter.h' file not found
#include "libxlsxwriter/include/xlsxwriter.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: rootcling: compilation failure (./TalysLibDictddf4371c70_dictUmbrella.h)

В директории TalysLib/libxlsxwriter похоже нет ни одного файла! Я что-то сделал не так, или в директории libxlsxwriter не хватает подключаемого файла?

**Comment by terawatt93** [comment]
Решено, 24.08.2021, в скрипт MakeLibraries.sh добавлена загрузка libxlsxwriter.
